name: Auto Like
on:
  schedule:
    # 日本時間 2:00, 4:00, 6:00 に実行
    # UTCでは前日の 17:00, 19:00, 21:00 になります
    - cron: '0 17,19,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install selenium
      - name: Run script
        env:
          RAKUTEN_CONFIG_JSON: ${{ secrets.RAKUTEN_CONFIG_JSON }}
        run: python GOOD.py
