name: Auto Like
on:
  schedule:
    # 日本時間 1, 3, 5, 7, 9, 11, 13, 15, 17, 19時に実行
    # UTCでは 16, 18, 20, 22, 0, 2, 4, 6, 8, 10時になります
    - cron: '0 0,2,4,6,8,10,16,18,20,22 * * *'
  workflow_dispatch: # 手動実行ボタンも残しておきます

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install selenium
      - name: Run script
        env:
          RAKUTEN_CONFIG_JSON: ${{ secrets.RAKUTEN_CONFIG_JSON }}
        run: python GOOD.py
